import type { ThemeConfig } from 'antd'

export const antdTheme: ThemeConfig = {
  components: {
    Button: {
      colorPrimary: 'var(--c-primary)',
      colorPrimaryHover: 'var(--c-primary)',
      colorPrimaryActive: 'var(--c-primary)',
      paddingInline: 24,
      // controlOutline: '#fff',
      // padding: 200,
      // paddingContentHorizontal: 200,
      // controlPaddingHorizontal: 200,
      // borderRadius: 20,
      // borderRadiusLG: 28,
      // borderRadiusSM: 15,
    },
    Input: {
      // paddingContentHorizontalLG: 20,
      // controlPaddingHorizontal: 20,
      controlHeight: 50,
      colorText: '#502FFF',
      fontSize: 18,
    },
    // Checkbox: {
    //  borderRadius: 2,
    //  borderRadiusOuter: 2,
    // },
    Tabs: {
      colorPrimary: 'var(--c-secondary)',
    },
  },
  token: {
    // colorPrimaryHover: '#628afe',
    // colorPrimaryActive: '#0142fe',
    // colorBgContainerDisabled: '#eef2f6',
    // colorBgContainer: '#141a29',
    // colorBgElevated: '#141a29',
    borderRadius: 8,
    borderRadiusLG: 10,
    borderRadiusSM: 8,
    // colorText: '#000',
    colorPrimary: 'var(--c-primary)',
    controlHeight: 48,
    // controlHeightLG: 56,
    // controlHeightSM: 30,
    // colorSuccess: '#0bbe7e',
    // colorError: '#ee152f',
    // colorWarning: '#f3c51f',
    fontFamily: 'Inter',
    fontSize: 16,
    fontSizeLG: 18,
    // paddingContentHorizontalSM: 10,
    // paddingContentHorizontalLG: 10,
    // paddingContentHorizontal: 20,
    // controlPaddingHorizontal: 20,
    fontSizeSM: 12,
  },
}
